### ISSUE TITLE
Save "read it later" bookmarks

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-chrome-extension#1]
See https://github.com/heutagogy/heutagogy-backend/issues/1.

Solution: when a user clicks on a button (or menu item), save the current page on the server. The extension should use the current link, title, and date. (User shouldn't enter any data.)

**Comment by drets** [comment]
@rasendubi should be closed as already implemented?

**Comment by rasendubi** [comment]
I think so. (Haven't tested yet.)
