### ISSUE TITLE
Fix tests on Travis.

### ISSUE THREAD

**Issue by drets** [heutagogy/heutagogy-chrome-extension#13]

**Comment by rasendubi** [comment]
#15 fixes Travis status, though it disables tests. @drets should we close the issue or keep it open while tests are not fixed too?

**Comment by drets** [comment]
@rasendubi close. On Travis we have linter and few integration tests (which were fixed).  
I haven't disabled any tests (I commented line with running unit tests for app, since we don't have any (yet)).
