### ISSUE TITLE
Detect duplicate bookmarks

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-chrome-extension#2]
Problem: I browse multiple information sources for new web pages to read, which results in saving the same page multiple times. As I'm only interested in reading every page once, I need a way to detect duplicates.

Solution: search for the link before saving. If the server already has it, notify the user and let him confirm he wants a duplicate.

**Comment by drets** [comment]
If you, guys, don't mind I'd like to tackle this issue.

**Comment by rasendubi** [comment]
You should not ask us. Do whatever you want. Anarchy yeah!

**Comment by drets** [comment]
I've just wanted to mark that I am going to work on it, so nobody grabs it.
