### ISSUE TITLE
Options page does not report request progress

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-chrome-extension#31]
Problem: when logging in, the options dialog does not report any progress. It's just saying "You are not logged in," so it's hard to tell if I got my username/password wrong or it's Heroku starting up the server, so it is responding slowly (or not responding at all).

Possible solutions:
1. Add a spinner, so I can tell if the request is in progress.
2. Report response status (like "you're logged in as <your name>", or "there is no user with such username and password", or "can't contact the server")

**Comment by drets** [comment]
It would be cool to add the second point (“Report response status”) to front repo too.

**Comment by drets** [comment]
ping @rasendubi

**Comment by rasendubi** [comment]
It would be good to improve error messages, but this issue is solved.
