### ISSUE TITLE
Response status is not checked on remembering article

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-chrome-extension#33]
Problem: when I click remember article slider, it immediately moves to "remembered" state. The issue is my token is invalid and the backend did not actually save my article.

Solution: wait for server response and only move slider if it is successful.

**Comment by drets** [comment]
What do you think about moving slider immediately, but if there is an error of saving article − move it back and show an error notification?

**Comment by rasendubi** [comment]
What happens if the backend is not responding for a while, so I just close the popup? I would add a spinner while request is in progress.

**Comment by drets** [comment]
>What happens if the backend is not responding for a while, so I just close the popup?

We might send “this article is not saved” notification using `chrome.notifications`.

**Comment by rasendubi** [comment]
I could be AFK by that time. (e.g., I click save, wait a second and go away.)
