### ISSUE TITLE
Configure server info

### ISSUE THREAD

**Issue by rasendubi** [heutagogy/heutagogy-chrome-extension#4]
Problem: I might use my own hosting for the server; the chrome extension should know where to address requests.

Solution: implement a settings page and let user fill the following info:
- server address
- user/pass (see https://github.com/heutagogy/heutagogy-backend/issues/2)

**Comment by Faradey27** [comment]
@rasendubi should we give simple users ability to change some configs? 

like we will have only 1 server and i think we want from users to use our servers

**Comment by rasendubi** [comment]
We should not limit our users. As we don't have a server now, the user should be able to configure the extension to use her one. (Even if we have, there are users who don't want to use our server.)

**Comment by drets** [comment]
I'd like to work on it next.

**Comment by Faradey27** [comment]
@drets thank you, 
i m currently don't have much time, maybe i will try to resolve some issues on this weekend
